### ISSUE TITLE
Abstract method error

### ISSUE THREAD

**Issue by abdulrahman86** [krasserm/akka-persistence-kafka#32]
Hi, 

I am getting this error when trying to use akka-persistence-kafka. 

Attaching my pom file. 

This is the error I get. 

java.lang.AbstractMethodError: akka.persistence.kafka.journal.KafkaJournal.akka$persistence$journal$WriteJournalBase$_setter_$persistence_$eq(Lakka/persistence/Persistence;)V
    at akka.persistence.journal.WriteJournalBase$class.$init$(WriteJournalBase.scala:15)
    at akka.persistence.kafka.journal.KafkaJournal.<init>(KafkaJournal.scala:22)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at java.lang.Class.newInstance(Class.java:442)
    at akka.util.Reflect$.instantiate(Reflect.scala:45)
    at akka.actor.NoArgsReflectConstructor.produce(Props.scala:361)
    at akka.actor.Props.newActor(Props.scala:252)
    at akka.actor.ActorCell.newActor(ActorCell.scala:552)
    at akka.actor.ActorCell.create(ActorCell.scala:578)
    at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
    at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
    at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
    at akka.dispatch.Mailbox.run(Mailbox.scala:219)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Please help, sort of need this urgently

[pom.txt](https://github.com/krasserm/akka-persistence-kafka/files/307860/pom.txt)

**Comment by krasserm** [comment]
This plugin doesn't work with Akka 2.4 yet. Put Akka 2.3 on your classpath.

**Comment by abdulrahman86** [comment]
I dont see 2.3 for akka persistence on maven central. is that even available? or you mean 2.3 just for akka actors

**Comment by krasserm** [comment]
http://repo1.maven.org/maven2/com/typesafe/akka/akka-persistence-experimental_2.11/

**Comment by abdulrahman86** [comment]
Thanks so much! So that error went away but now I get this. 

akka.actor.InvalidActorNameException: actor name [snapshot-store] is not unique!

Attaching file for my persistent actor 

[actor.txt](https://github.com/krasserm/akka-persistence-kafka/files/309277/actor.txt)

Also attaching my app.conf file 

[application-conf.txt](https://github.com/krasserm/akka-persistence-kafka/files/309279/application-conf.txt)

**Comment by krasserm** [comment]
Does adding `akka.persistence.snapshot-store.plugin = "kafka-snapshot-store"` to your application config help?
